language: ruby
rvm:
  - 2.6.1

# bundler_args: config force_ruby_platform true

jobs:
  include:
    - stage: test
      script:
        - bundle exec gem install rubocop
        - bundle exec rake rubocop
        - bundle exec rails test
    # - stage: build
    #   script: bundle exec rails s