jobs:
  include:
    - stage: test
    - stage: build

rubocop:
  stage: test
  script: 
  - bundle exec gem install rubocop
  - bundle exec rake rubocop

railstest:
  stage: test
  script: 
  - bundle exec rails test

build:
  stage: build
  script: 
  - bundle exec rails s
